#!/bin/bash

# ------------------------- [START] set shell options ------------------------ #
# exit script immediately if anything errors
set -e

# allow tracing to be toggled on
if [ "$DEBUG_GKE_GLUSTERFS_HEKETI" = 'true' ]
then
  set -x
fi
# -------------------------- [END] set shell options ------------------------- #

# ------------------------- [START] get project path ------------------------- #
# get full path to this project
project_dir="$(cd -P -- "$(dirname -- "$0")" 2>&1 > /dev/null && pwd -P)"

# check that the project directory didn't turn out empty
if [ -z "$project_dir" ]
then
  echo "Some error occured getting the full path to this project's directory."

  # this is intended to be sourced instead of executed so we return
  # instead of exiting so we don't exit the shell session entirely
  return 1
fi
# -------------------------- [END] get project path -------------------------- #

# ------------------------ [START] source config file ------------------------ #
. "$project_dir/config"
# ------------------------- [END] source config file ------------------------- #

# ---------------------- [START] set required variables ---------------------- #
export project_name="$CLOUDSDK_PROJECT_NAME"
export cluster_name="$CLOUDSDK_CLUSTER_NAME"
export zone="$CLOUDSDK_COMPUTE_ZONE"
# ----------------------- [END] set required variables ----------------------- #

# ---------------------- [START] set optional variables ---------------------- #
# cluster version will default to whatever GKE's default is at the time
export cluster_version="$CLUSTER_VERSION"
export node_count=${NODE_COUNT:-'3'}
export machine_type=${MACHINE_TYPE:-'n1-standard-1'}
export disk_size=${DISK_SIZE:-'20'}

export docker_registry=${DOCKER_REGISTRY:-"gcr.io/$project_name"}
export docker_image_name=${DOCKER_IMAGE_NAME:-'glusterfs-heketi-bootstrap'}
export docker_image_version=${DOCKER_IMAGE_VERSION:-'0.0.1'}

# if DOCKER_IMAGE_NAME was not configured, defaults to the public dockerhub
# image at https://hub.docker.com/r/stevenaldinger/gke-glusterfs-heketi/
if [ -z "$DOCKER_IMAGE_NAME" ]
then
  # my public dockerhub
  export job_image='stevenaldinger/gke-glusterfs-heketi:latest'
else
  # my private gcr repo
  export job_image="gcr.io/$project_name/$docker_image_name:$docker_image_version"
fi
# ----------------------- [END] set optional variables ----------------------- #

# ---------------- [START] ensure script requirements are met ---------------- #
script_requirements_met='true'

if [ -z "$(which gcloud)" ]
then
  echo "You need gcloud installed."
  echo "Visit https://cloud.google.com/sdk/downloads to download the latest version."

  script_requirements_met='false'
fi

if [ -z "$(which kubectl)" ]
then
  echo "You need kubectl installed."
  echo "If you already have gcloud installed, run 'gcloud components install kubectl'."
  script_requirements_met='false'
fi

if [ -z "$project_name" ] || [ -z "$cluster_name" ] || [ -z "$zone" ]
then
  echo "You're missing required config variables."
  echo "Make sure there are values for everything under \"required variables\" in $project_dir/config"

  script_requirements_met='false'
fi

if [ "$node_count" -lt 3 ]
then
  echo "You need at least 3 nodes in the cluster for Heketi to run properly"

  script_requirements_met='false'
fi

if [ "$script_requirements_met" = 'false' ]
then
  # this is intended to be sourced instead of executed so we return
  # instead of exiting so we don't exit the shell session entirely
  return 1
fi
# ----------------- [END] ensure script requirements are met ----------------- #

# ------------------------- [START] helper functions ------------------------- #
trim_whitespace () {
	local var=$@
  # remove leading whitespace characters
	var="${var#"${var%%[![:space:]]*}"}"
  # remove trailing whitespace characters
	var="${var%"${var##*[![:space:]]}"}"
	echo -n "$var"
}


gke_glusterfs_heketi_build_image () {
  if [ -z "$(which docker)" ]
  then
    echo "You need docker installed to build this image."
  else
    docker build -t "$docker_registry/$docker_image_name:$docker_image_version" "$project_dir"
  fi
}

gke_glusterfs_heketi_push_image () {
  docker push "$docker_registry/$docker_image_name:$docker_image_version"
}

gke_glusterfs_heketi_generate_k8s () {
  rm -rf "$project_dir/k8s"

  mkdir -p "$project_dir/k8s"

  cat > "$project_dir/k8s/00-namespace.yaml" <<EOF
---
apiVersion: v1
kind: Namespace
metadata:
  name: glusterfs-heketi-bootstrap
EOF

cat > "$project_dir/k8s/01-configmap.yaml" <<EOF
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glusterfs-heketi-bootstrap
  namespace: glusterfs-heketi-bootstrap
data:
  project-id: $project_name
  cluster-name: $cluster_name
  cluster-zone: $zone
  cluster-node-count: "$node_count"
  disk-size: "$disk_size"
EOF

cat > "$project_dir/k8s/01-heketi-clusterrolebinding.yaml" <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: glusterfs-heketi-bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: glusterfs-heketi-bootstrap
    namespace: glusterfs-heketi-bootstrap
EOF

cat > "$project_dir/k8s/02-job.yaml" <<EOF
---
apiVersion: batch/v1
kind: Job
metadata:
  name: glusterfs-heketi-bootstrap
  namespace: glusterfs-heketi-bootstrap
spec:
  template:
    metadata:
      name: glusterfs-heketi-bootstrap
    spec:
      restartPolicy: Never
      containers:
      - name: glusterfs-heketi-bootstrap
        image: $job_image
        securityContext:
          capabilities: {}
          privileged: true
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: project-id
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: cluster-name
        - name: ZONE
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: cluster-zone
        - name: NODE_COUNT
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: cluster-node-count
        - name: DISK_SIZE
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: disk-size
EOF
}

gke_glusterfs_heketi_delete_gluster_disks () {
  disk_count=0
  disk_list=""

  echo "Deleting..."
  for disk in $(gcloud compute disks list --format="table(name)" --filter="description=${cluster_name}-gfs-k8s-brick")
  do
    if [ "$disk_count" -eq 0 ]
    then
      # do nothing, the first returned is just a table header
      echo ""
    else
      disk_list="$disk_list $disk"
    fi

    disk_count=$((disk_count + 1))
  done

  gcloud compute disks delete --quiet $disk_list
}

gke_glusterfs_heketi_deploy_glusterfs_heketi () {
  kubectl apply -f "$project_dir/k8s"
}

gke_glusterfs_heketi_create_cluster () {
  "$project_dir/scripts/create-cluster.sh"
}

_gke_glusterfs_heketi_create_service_account () {
  kubectl create serviceaccount \
    glusterfs-heketi-bootstrap \
    --namespace glusterfs-heketi-bootstrap
}

_gke_glusterfs_heketi_add_admin_clusterrolebinding () {
  kubectl apply -f "$project_dir/k8s/01-heketi-clusterrolebinding.yaml"
}

_gke_glusterfs_heketi_allow_own_user_rbac_admin () {
  # outputs something like this:
  # account = me@stevenaldinger.com
  email_unclean=$(gcloud config list | grep account)

  # remove the 'account = '
  email_clean_untrimmed=${email_unclean#*=}

  email_clean="$(trim_whitespace $email_clean_untrimmed)"

  kubectl create clusterrolebinding \
    "$email_clean-cluster-admin-binding" \
    "--clusterrole=cluster-admin" \
    "--user=$email_clean"
}

_gke_glusterfs_heketi_allow_default_compute_rbac_admin () {
  # outputs something like this:
  # Compute Engine default service account  789491211420-compute@developer.gserviceaccount.com
  email_unclean=$(gcloud iam service-accounts list | grep "Compute Engine default service account")

  # remove the 'Compute Engine default service account '
  email_clean_untrimmed=${email_unclean#*"service account"}

  email_clean="$(trim_whitespace $email_clean_untrimmed)"

  kubectl create clusterrolebinding \
    "$email_clean-cluster-admin-binding" \
    "--clusterrole=cluster-admin" \
    "--user=$email_clean"
}

gke_glusterfs_heketi_configure_rbac () {
  # requires namespace already be created
  kubectl apply -f k8s/00-namespace.yaml

  _gke_glusterfs_heketi_allow_own_user_rbac_admin

  # default_compute necessary to avoid error during job:
  # Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "789491211420-compute@developer.gserviceaccount.com" cannot create clusterrolebindings.rbac.authorization.k8s.io at the cluster scope: Required "container.clusterRoleBindings.create" permission.
  # Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "heketi-sa-view" not found
  _gke_glusterfs_heketi_allow_default_compute_rbac_admin

  _gke_glusterfs_heketi_create_service_account

  _gke_glusterfs_heketi_add_admin_clusterrolebinding
}

gke_glusterfs_heketi_delete_cluster () {
  gcloud container clusters delete "$cluster_name" --quiet
}

gke_glusterfs_heketi_delete_cluster_and_disks () {
  gke_glusterfs_heketi_delete_cluster && \
  gke_glusterfs_heketi_delete_gluster_disks && \
  gcloud compute firewall-rules delete allow-glusterfs --quiet
}

gke_glusterfs_heketi_tail_job_logs () {
  kubectl -n glusterfs-heketi-bootstrap logs -f "$(kubectl get po -n glusterfs-heketi-bootstrap -l job-name=glusterfs-heketi-bootstrap -o jsonpath='{.items[0].metadata.name}')"
}

gke_glusterfs_heketi_if_storage_class_not_found_during_k8s_example_run_me () {
  external_ip_first_node=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}')
  heketi_nodeport=$(kubectl get svc/heketi -n default -o jsonpath='{.spec.ports[0].nodePort}')

  storage_class_yaml_path="$project_dir/k8s/heketi-glusterfs-storage-class.yaml"

  # ---------------- [START] Generate storage class descriptor ----------------- #
  cat > "$storage_class_yaml_path" <<EOF
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: glusterfs-storage
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Retain
parameters:
  resturl: "http://${external_ip_first_node}:${heketi_nodeport}"
EOF
  # ----------------- [END] Generate storage class descriptor ------------------ #

  # ----------------------- [START] Apply storage class ------------------------ #
  kubectl apply -f "$storage_class_yaml_path"
  # ------------------------ [END] Apply storage class ------------------------- #
}

create_etcd_rbac_roles () {
  cd ./k8s-example/etcd/rbac/
  ./create_role.sh
  cd -
}

deploy_etcd_operator_and_cluster () {
  kubectl apply -f ./k8s-example/etcd/operator-deployment.yaml
  kubectl apply -f ./k8s-example/etcd/cluster-deployment.yaml
}

deploy_example_wordpress_and_mariadb () {
  kubectl apply -f k8s-example/_configmaps
  kubectl apply -f k8s-example/_secrets

  # kubectl apply -f k8s-example/mariadb/01-persistent-volume-claim.yaml
  # kubectl apply -f k8s-example/mariadb/01.service.yaml
  # kubectl apply -f k8s-example/mariadb/02-statefulset.yaml

  kubectl apply -f k8s-example/percona/01.persistent-volume-claim.yaml
  kubectl apply -f k8s-example/percona/01.service.yaml
  kubectl apply -f k8s-example/percona/02.statefulset.yaml

  # give db time to initialize
  sleep 120

  kubectl apply -f k8s-example/wordpress/01-persistent-volume-claim.yaml
  kubectl apply -f k8s-example/wordpress/01.service.yaml
  # kubectl apply -f k8s-example/wordpress/02-deployment.yaml
  kubectl apply -f k8s-example/wordpress/02-statefulset.yaml
}

delete_example_wordpress_and_mariadb () {
  kubectl delete -f k8s-example/_configmaps
  kubectl delete -f k8s-example/_secrets

  # kubectl delete -f k8s-example/mariadb/01-persistent-volume-claim.yaml
  # kubectl delete -f k8s-example/mariadb/01.service.yaml
  # kubectl delete -f k8s-example/mariadb/02-statefulset.yaml

  kubectl delete -f k8s-example/percona/01.persistent-volume-claim.yaml
  kubectl delete -f k8s-example/percona/01.service.yaml
  kubectl delete -f k8s-example/percona/02.statefulset.yaml

  kubectl delete -f k8s-example/wordpress/01-persistent-volume-claim.yaml
  kubectl delete -f k8s-example/wordpress/01.service.yaml
  kubectl delete -f k8s-example/wordpress/02-statefulset.yaml
  # kubectl delete -f k8s-example/wordpress/02-deployment.yaml
}
# -------------------------- [END] helper functions -------------------------- #

# --------------------------- [START] print config --------------------------- #
echo "---------------------------------------------"
echo "Functions available:"
echo "- gke_glusterfs_heketi_build_image"
echo "- gke_glusterfs_heketi_push_image"
echo "- gke_glusterfs_heketi_generate_k8s"
echo "- gke_glusterfs_heketi_configure_rbac"
echo "- gke_glusterfs_heketi_delete_gluster_disks"
echo "- gke_glusterfs_heketi_deploy_glusterfs_heketi"
echo "- gke_glusterfs_heketi_create_cluster"
echo "- gke_glusterfs_heketi_delete_cluster"
echo "- gke_glusterfs_heketi_delete_cluster_and_disks"
echo "- deploy_example_wordpress_and_mariadb"
echo "- delete_example_wordpress_and_mariadb"
echo "- deploy_etcd_operator_and_cluster"
echo "- create_etcd_rbac_roles"
echo ""
echo "---------------------------------------------"
echo "Current config:"
echo "- CLOUDSDK_PROJECT_NAME = $project_name"
echo "- CLOUDSDK_CLUSTER_NAME = $cluster_name"
echo "- CLOUDSDK_COMPUTE_ZONE = $zone"
echo "- CLUSTER_VERSION       = $cluster_version"
echo "- NODE_COUNT            = $node_count"
echo "- MACHINE_TYPE          = $machine_type"
echo "- DOCKER_REGISTRY       = $docker_registry"
echo "- DOCKER_IMAGE_NAME     = $docker_image_name"
echo "- DOCKER_IMAGE_VERSION  = $docker_image_version"
echo "---------------------------------------------"
# ---------------------------- [END] print config ---------------------------- #

# --------------- [START] execute command if argument provided --------------- #
if [ ! -z "$1" ]
then
  $1
else
  echo ""
  echo "This script can be run with arguments or by sourcing and calling the functions directly."
  echo "Try './helpers gke_glusterfs_heketi_build_image'"
fi
# ---------------- [END] execute command if argument provided ---------------- #

# ------------------------ [START] unset shell options ----------------------- #
# exit script immediately if anything errors
set +e

# allow tracing to be toggled on
if [ "$DEBUG_GKE_GLUSTERFS_HEKETI" = 'true' ]
then
  set +x
fi
# ------------------------- [END] unset shell options ------------------------ #
