---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: default
  labels:
    component: mariadb
spec:
  serviceName: mariadb
  replicas: 1
  template:
    metadata:
      name: mariadb
      namespace: default
      labels:
        component: mariadb
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.26.2"
        imagePullPolicy: Always
        command:
        - "rm"
        - "-rf"
        - "/var/lib/mysql/lost+found"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-volume
      containers:
      - name: mariadb
        image: mariadb:10.3.1
        args:
        - mysqld
        - --bind-address=0.0.0.0
        ports:
        - name: http
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: example
        volumeMounts:
        - name: mariadb-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-volume
        persistentVolumeClaim:
          claimName: mariadb
